# Transformation Convention Summary

In transformations between frames A and B:

- **Subscript** denotes the frame that the vector is expressed in.
- **Superscript** denotes the frame that the vector is transformed into.

## Transforming from Frame A to Frame B and Expressing Frame A in Frame B

- **Notation**: \( T_{AB} \) (Transformation from frame A to frame B) and \( ^B T_A \) (Frame A expressed in frame B)
- **Interpretation**: A relative to B
- **Example**: Transforming a vector from frame A to frame B or expressing the position or orientation of frame A relative to frame B


In [5]:
import numpy as np
from scipy.spatial.transform import Rotation


# Base relative to IMU, T_BI, R_BI  
B_r_BI = np.array([-0.01775, 0.006, 0.058])  # Translation from IMU to Body frame
q_BI = np.array([0.000000, 0.000000, 0.707106781186548, 0.707106781186548])  # Quaternion from IMU to Body frame
r_BI = Rotation.from_quat(q_BI).as_matrix()
T_BI = np.eye(4)
T_BI[:3, :3] = r_BI
T_BI[:3, 3] = B_r_BI

# Base relative to Lidar, T_BL, R_BL 
B_r_BL = np.array([-0.00042, -0.008, 0.135446])  # Translation from Lidar to Body frame
q_BL = np.array([-0.001596, 0.005182, 0.708182, 0.706009])  # Quaternion from Lidar to Body frame
r_BL = Rotation.from_quat(q_BL).as_matrix()
T_BL = np.eye(4)    
T_BL[:3, :3] = r_BL
T_BL[:3, 3] = B_r_BL

# Rotation from Lidar to IMU:      
R_BL_to_BI = Rotation.from_quat(q_BI).as_matrix() @ Rotation.from_quat(q_BL).as_matrix().T

# Translation from Lidar to IMU
T_BL_to_BI = B_r_BI - R_BL_to_BI @ B_r_BL

print("\nTranslation Vector (T_BL_to_BI):\n", T_BL_to_BI)
print("Rotation Matrix (R_BL_to_BI):")
print(R_BL_to_BI)

# LiDAR -> IMU Transformation Matrix 
T_LI = T_BI @ np.linalg.inv(T_BL)
print("\nTransformation Matrix (T_LI):\n", T_LI)



Translation Vector (T_BL_to_BI):
 [-0.01661674  0.01529554 -0.07735917]
Rotation Matrix (R_BL_to_BI):
[[ 0.99998242  0.00304873 -0.00508602]
 [-0.00309734  0.99994934 -0.0095776 ]
 [ 0.00505656  0.00959318  0.9999412 ]]

Transformation Matrix (T_LI):
 [[ 0.99998242  0.00304873 -0.00508602 -0.01661674]
 [-0.00309734  0.99994934 -0.0095776   0.01529554]
 [ 0.00505656  0.00959318  0.9999412  -0.07735917]
 [ 0.          0.          0.          1.        ]]
